exports.BattleLearnsets = {
        viterb:{learnset:{agility:["5L42"],aquatail:["5E"],aromatherapy:["5E"],bite:["5L26"],bodyslam:["5L32"],brickbreak:["5M"],bulletseed:["5L24"],crunch:["5E"],cut:["5M"],dragontail:["5E"],dig:["5M"],doubleteam:["5M"],dragonclaw:["5M"],energyball:["5M"],frustration:["5M"],grassknot:["5M"],grasspledge:["5T"],growl:["5L1"],hiddenpower:["5M"],leafblade:["5L49"],leechseed:["5L19"],payback:["5M"],poisonjab:["5M"],pound:["5E"],protect:["5M"],rest:["5M"],return:["5M"],roar:["5L39","5M"],rockblast:["5L29"],rockslide:["5L45","5M"],rocksmash:["5L21","5M"],rockthrow:["5L10"],seedbomb:["5L35"],shadowclaw:["5M"],solarbeam:["5M"],stealthrock:["5E"],stoneedge:["5L54"],substitute:["5M"],swagger:["5M"],tackle:["5L1"],tailwhip:["5L15"],taunt:["5M"],toxic:["5M"],vinewhip:["5L7"],worryseed:["5L17"],xscissor:["5M"]}},
        hierbado:{learnset:{agility:["5L42"],aquatail:["5E"],aromatherapy:["5E"],bite:["5L26"],bodyslam:["5L32"],brickbreak:["5M"],bulletseed:["5L24"],crunch:["5E"],cut:["5M"],dragontail:["5E"],dig:["5M"],doubleteam:["5M"],dragonclaw:["5M"],energyball:["5M"],frustration:["5M"],grassknot:["5M"],grasspledge:["5T"],growl:["5L1"],hiddenpower:["5M"],leafblade:["5L49"],leechseed:["5L19"],payback:["5M"],poisonjab:["5M"],pound:["5E"],protect:["5M"],rest:["5M"],return:["5M"],roar:["5L39","5M"],rockblast:["5L29"],rockslide:["5L45","5M"],rocksmash:["5L21","5M"],rockthrow:["5L10"],seedbomb:["5L35"],shadowclaw:["5M"],solarbeam:["5M"],stealthrock:["5E"],stoneedge:["5L54"],substitute:["5M"],swagger:["5M"],tackle:["5L1"],tailwhip:["5L15"],taunt:["5M"],toxic:["5M"],vinewhip:["5L7"],worryseed:["5L17"],xscissor:["5M"]}},
        rapagram:{learnset:{agility:["5L42"],bite:["5L26"],bodyslam:["5L32"],brickbreak:["5M"],bulletseed:["5L24"],crunch:["5L1"],cut:["5M"],dragontail:["5E"],dig:["5M"],doubleteam:["5M"],dragonclaw:["5M"],earthquake:["5M"],energyball:["5M"],frenzyplant:["5T"],frustration:["5M"],gigaimpact:["5M"],grassknot:["5M"],grasspledge:["5T"],growl:["5L1"],hiddenpower:["5M"],hyperbeam:["5M"],leafblade:["5L49"],leechseed:["5L19"],payback:["7M"],poisonjab:["7M"],protect:["5M"],psychic:["5M"],rest:["5M"],return:["5M"],roar:["5L39","5M"],rockblast:["5L29"],rockpolish:["5M"],rockslide:["5L45","5M"],rocksmash:["5L21","5M"],rockthrow:["5L10"],sandstorm:["5M"],seedbomb:["5L35"],shadowclaw:["5M"],shadowball:["5M"],solarbeam:["5M"],stoneedge:["7L54"],strength:["7M"],substitute:["7M"],swagger:["5M"],swordsdance:["5M"],tackle:["5L1"],tailwhip:["5L15"],taunt:["5M"],toxic:["5M"],vinewhip:["5L7"],woodhammer:["5L1"],worryseed:["5L17"],xscissor:["5M"]}},
        gazceit:{learnset:{batonpass:["5E"],doublekick:["5E"],flamecharge:["5L36"],hornleech:["5E"],quickattack:["5L3"],return:["5M"],substitute:["5M"],swordsdance:["5M"],voidhorn:["5L59"],wildcharge:["5M"]}},
        ninjantis:{learnset:{hijumpkick:["5L57"],substitute:["5M"],swordsdance:["5L38","5M"],uturn:["5M"],xscissor:["5L44","5M"]}},
        manjitsu:{learnset:{hijumpkick:["5L57"],substitute:["5M"],swordsdance:["5L38","5M"],uturn:["5M"],xscissor:["5L44","5M"]}},
        witcheance:{learnset:{calmmind:["5M"],destinybond:["5L59"],energyball:["5L35","5M"],focusblast:["5M"],spore:["5L71"],thunderbolt:["5M"],vendetta:["5L66"],willowisp:["5M"]}},
        aguilari:{learnset:{aerialace:["5L1"],bravebird:["5L68"],bulkup:["5L60","5M"],circlethrow:["5L56"],divingtalon:["5L18"],pursuit:["5L32"],rockblast:["5L64"],stormthrow:["5L1"]}},
        komolten:{learnset:{bulkup:["5M"],dragondance:["5M71"],earthquake:["5L61","5M"],flareblitz:["5E"],firerocket:["5L19"],stoneedge:["5M"],wildcharge:["5M"]}}
};
